language: python
python:
  - "2.7"
  - "3.3"
install:
  - pip install python-coveralls --use-mirrors
  - pip install -r requirements.txt --use-mirrors
script: coverage run -m discover
after_success:
  - coveralls
